name: Atmos Terraform Apply
run-name: apply ${{ inputs.component }}/${{ inputs.stack }}

on:
  workflow_dispatch:
    inputs:
      component:
        description: "Component"
        required: true
        type: string
      stack:
        description: "Stack"
        required: true
        type: string
      sha:
        description: "Commit SHA"
        type: string
      github_environment:
        description: "GitHub Environment"
        required: true
        type: string

permissions:
  id-token: write
  contents: read
  checks: write
  statuses: write

env:
  ATMOS_PROFILE: github
  APP_IMAGE: "${{ vars.ECR_REGISTRY }}/cloudposse-examples/atmos-pro-with-ecs:sha-${{ inputs.sha }}"

jobs:
  apply:
    name: ${{ inputs.component }}-${{ inputs.stack }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    defaults:
      run:
        shell: bash
    environment:
      name: ${{ inputs.github_environment }}
      url: ${{ steps.deploy.outputs.output_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.sha }}

      - name: Deploy
        id: deploy
        shell: bash
        env:
          ATMOS_PRO_WORKSPACE_ID: ${{ vars.ATMOS_PRO_WORKSPACE_ID }}
          ATMOS_PRO_BASE_URL: ${{ vars.ATMOS_PRO_BASE_URL }}          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_SHA: ${{ inputs.sha }}
        run: |
          atmos terraform deploy ${{ inputs.component }} -s ${{ inputs.stack }} --upload-status
