name: Atmos Pro
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, closed]
  merge_group:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  checks: write
  statuses: write

env:
  ATMOS_PROFILE: github

jobs:
  test:
    needs: [ build ]
    if: |
      github.event_name != 'pull_request' ||
      github.event.action != 'closed' ||
      github.event.pull_request.merged == true
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: app/go.mod
          cache-dependency-path: app/go.mod

      - name: Run tests
        working-directory: app
        run: go test -v ./...

  build:
    if: |
      github.event_name != 'pull_request' ||
      github.event.action != 'closed' ||
      github.event.pull_request.merged == true
    runs-on: ["ubuntu-latest"]
    steps:
      - name: Install Atmos
        uses: cloudposse/github-action-setup-atmos@v3
        with:
          install-wrapper: false
          atmos-version: ${{ vars.ATMOS_VERSION }}
              
      - name: Checkout
        uses: actions/checkout@v6

      - name: AWS Auth
        run: |
          atmos auth env --identity plat-dev/terraform --format=github
          atmos auth login --identity plat-dev/terraform

      - name: Build
        id: build
        uses: cloudposse/github-action-docker-build-push@v3
        with:
          organization: cloudposse-sandbox
          repository: atmos-pro-with-ecs
          registry: ${{ vars.ECR_REGISTRY }}
          workdir: app
          driver-opts: image=mirror.gcr.io/moby/buildkit:buildx-stable-1

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}

  affected:
    needs: [ test, build ]
    name: Trigger Affected Stacks
    runs-on: ["ubuntu-latest"]
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    defaults:
      run:
        shell: bash
    if: |
      github.event_name == 'merge_group' ||
      github.event.pull_request.merged == true ||
      (
        github.event.action != 'closed' &&
        !contains(github.event.pull_request.labels.*.name, 'no-apply')
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # ref: ${{ github.event.pull_request.merged && github.event.pull_request.merge_commit_sha || github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Determine Affected Stacks
        env:
          ATMOS_PRO_WORKSPACE_ID: ${{ vars.ATMOS_PRO_WORKSPACE_ID }}
          ATMOS_PRO_BASE_URL: ${{ vars.ATMOS_PRO_BASE_URL }}          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          atmos describe affected --upload
